"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import {CartButton} from "@/components/cart";
import {useRouter} from "next/navigation";
import {products,categories,assetImage,whatsapp} from "@/lib/catalog";
import {ProductCard} from "@/components/catalog-view";

const filters = ["All Products", ...categories.map(c => c.name)];
const mail = (subject: string, body = "") => `mailto:hello@apkina.pk?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
function Icon({ name, className = "" }: { name: string; className?: string }) { return <img className={`icon ${className}`} src={`/assets/${name}.svg`} alt="" width="24" height="24" />; }
type Info = { title: string; body: string; action?: string; subject?: string };

export default function Home() {
 const router=useRouter();
 const [category, setCategory] = useState("All Products");
 const [menuOpen, setMenuOpen] = useState(false);
 const [searchOpen, setSearchOpen] = useState(false);
 const [info, setInfo] = useState<Info | null>(null);
 const [query, setQuery] = useState("");
 const [scrolled, setScrolled] = useState(false);
 const [email, setEmail] = useState("");
 const [subscription, setSubscription] = useState<"idle" | "loading" | "success" | "error">("idle");
 const [formMessage, setFormMessage] = useState("");
 const heroRef = useRef<HTMLElement>(null);
 useEffect(() => {
   const motion = window.matchMedia("(prefers-reduced-motion: reduce)");
   const onScroll = () => { setScrolled(window.scrollY > 80); if (!motion.matches) heroRef.current?.style.setProperty("--parallax", `${Math.min(window.scrollY * .07, 55)}px`); };
   onScroll(); window.addEventListener("scroll", onScroll, { passive: true });
   return () => window.removeEventListener("scroll", onScroll);
 }, []);
 useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: .08 }); document.querySelectorAll(".reveal").forEach(el => observer.observe(el)); return () => observer.disconnect(); }, [category]);
 const browse = (value = "All Products") => { router.push(value === "All Products" ? "/shop" : `/category/${categories.find(c=>c.name===value)?.slug || "lighting"}`); };
 useEffect(() => {
   type Registry = { registerTool: (tool: { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean }; execute: (input: unknown) => Promise<object> }, options: { signal: AbortSignal }) => void | Promise<void> };
   const context = (document as Document & { modelContext?: Registry }).modelContext;
   if (!context?.registerTool) return;
   const lifecycle = new AbortController();
   try { void Promise.resolve(context.registerTool({ name: "browse_product_category", title: "Browse product category", description: "Navigate to the selected product category. Does not purchase or send messages.", inputSchema: { type: "object", properties: { category: { type: "string", enum: filters } }, required: ["category"], additionalProperties: false }, annotations: { readOnlyHint: false }, async execute(input: unknown) {
     const value = input && typeof input === "object" ? (input as { category?: unknown }).category : undefined;
     if (typeof value !== "string" || !filters.includes(value)) throw new Error("Choose a valid product category.");
     browse(value);
     await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
     return { category: value, view: "product catalog" };
   } }, { signal: lifecycle.signal })).catch(() => {}); } catch {}
   return () => lifecycle.abort();
 }, []);
 const contact = (channel: string) => {if(channel === "WhatsApp") window.open(whatsapp("Hello Apkina! I need some help with my setup."),"_blank","noopener,noreferrer"); else if(channel === "Call us") window.location.href="tel:+923252849975";else router.push("/contact");};
 const blog = () => router.push("/blog");
 const legal = (title: string) => setInfo({ title, body: title === "Privacy Policy" ? "Your newsletter email is stored so Apkina can provide updates and promotional offers. Your bag is saved only for this browser session. To request removal of your subscription, email hello@apkina.pk." : title === "Cookie Usage" ? "This site uses session storage to keep your current bag. The storefront does not set advertising or analytics cookies." : "Please contact the Apkina team for current purchasing, shipping, returns, and warranty terms before placing an order.", action: "Contact Apkina", subject: title });
 async function subscribe(event: FormEvent<HTMLFormElement>) {
   event.preventDefault(); const form = new FormData(event.currentTarget); setSubscription("loading"); setFormMessage("");
   try { const response = await fetch("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, website: form.get("website") }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Please try again."); setSubscription("success"); setFormMessage("You're on the list. Thank you for joining Apkina."); }
   catch (error) { setSubscription("error"); setFormMessage(error instanceof Error ? error.message : "Please try again, or email hello@apkina.pk."); }
 }
 const searchText = query.trim().toLowerCase();
 const searchCategories = categories.filter(c => `${c.name} ${c.description}`.toLowerCase().includes(searchText));
 const searchProducts = products.filter(p=>!searchText || `${p.name} ${p.summary}`.toLowerCase().includes(searchText));
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className={`site-header ${scrolled ? "scrolled" : ""}`}>
   <a href="#home" className="brand" aria-label="Apkina home"><img src="/assets/logo.svg" alt="Apkina" width="121" height="30" /></a>
   <nav className="desktop-nav" aria-label="Main navigation"><a href="#home">Home</a><DropdownMenu><DropdownMenuTrigger className="shop-trigger">Shop <Icon name="chevron" /></DropdownMenuTrigger><DropdownMenuContent className="shop-dropdown" align="center"><DropdownMenuItem onSelect={() => browse()}>All Products</DropdownMenuItem>{categories.map(c => <DropdownMenuItem key={c.name} onSelect={() => browse(c.name)}>{c.name}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><a href="#about">About</a><button onClick={blog}>Blog</button><a href="/contact">Contact</a></nav>
   <div className="header-actions"><button className="icon-button" aria-label="Search products" onClick={() => setSearchOpen(true)}><Icon name="search" /></button><button className="icon-button account-button" aria-label="Customer care" onClick={() => contact("Customer care")}><Icon name="account" /></button><CartButton/><button className="icon-button menu-button" aria-label="Open menu" onClick={() => setMenuOpen(true)}><span /><span /></button></div>
  </header>
  <main id="main">
   <section id="home" ref={heroRef} className="hero" aria-labelledby="hero-title"><div className="hero-gradient" aria-hidden="true" /><div className="hero-vignette" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow">Professional RGB Light</p><h1 id="hero-title" className="silver-text">AP1000</h1><p className="hero-tagline">Make every colour count</p><button className="pill light" onClick={() => browse("Lighting")}>View Collection</button></div><div className="hero-product"><img src="/assets/hero.png" alt="Apkina AP1000 professional RGB light glowing violet" width="412" height="617" fetchPriority="high" /></div></section>
   <section className="categories section-container section-space" id="categories" aria-labelledby="category-heading"><div className="section-intro reveal"><h2 id="category-heading">Everything you need <span>for a perfect shot</span></h2><p>Build your setup with dependable tools for photography, filmmaking, content creation and studio production</p></div><div className="category-grid">{categories.map((c, i) => <button className="category-card reveal" key={c.name} style={{ "--delay": `${i % 3 * 70}ms` } as React.CSSProperties} onClick={() => browse(c.name)}><img src={assetImage(({tripods:"tripods",modifiers:"lighting",lighting:"product",accessories:"accessories",speedlights:"speedlights",audio:"audio"} as Record<string,string>)[c.slug])} alt="" width="100" height="100" loading="lazy" /><h3>{c.name}</h3><p>{c.description}</p><span className="category-arrow" aria-hidden="true">↗</span></button>)}</div></section>
   <section className="story production section-space" id="creators"><img className="story-background" src="/assets/production.png" alt="Creator filming a studio production with blue and orange light" width="1440" height="900" loading="lazy" /><div className="story-copy reveal"><p className="eyebrow">Built for real productions</p><h2 className="silver-text">Control the mood.<br /> Own the frame.</h2><p>Portraits, products, interviews, films and reels. Apkina lighting adapts to the way you work, whether you’re creating in a studio or on location.</p><button className="pill light" onClick={() => browse("Lighting")}>Find Your Light</button></div></section>
   <section id="products" className="products section-container section-space" aria-labelledby="products-heading"><h2 id="products-heading" className="centered-heading reveal">Find the missing piece <span>for your content.</span></h2><Tabs value={category} onValueChange={setCategory} className="product-tabs"><div className="tab-scroll"><TabsList className="filter-list" aria-label="Product categories">{filters.map(name => <TabsTrigger value={name} key={name} className="filter-tab">{name}</TabsTrigger>)}</TabsList></div>{filters.map(name => <TabsContent key={name} value={name} className="product-panel"><p className="demo-notice">Ask us for current pricing and availability.</p><div className="product-grid">{(name === "All Products" ? ["100-pro-rgb","tm264a-lp36","90-cm-octa-softbox","ap1000","ds1-mobile-rig","ap11ii-11-inch-panel-light-with-remote"].map(slug=>products.find(p=>p.slug===slug)!) : products.filter(p=>p.category===categories.find(c=>c.name===name)?.slug).slice(0,6)).map(p=><ProductCard key={p.slug} product={p}/>)}</div></TabsContent>)}</Tabs><a className="pill outline view-more" href="/shop">View All Products</a></section>
   <section className="story philosophy section-space" id="about"><img className="story-background" src="/assets/philosophy.png" alt="Pakistani creator working with a camera in a dramatically lit studio" width="1440" height="901" loading="lazy" /><div className="story-copy reveal"><p className="eyebrow">The Apkina philosophy</p><h2 className="silver-text">Built for every frame, sound, and story</h2><p>From light and sound to support and control, Apkina helps creators turn ideas into work people remember. We make professional creative tools for the people shaping Pakistan’s visual culture.</p><button className="pill light" onClick={() => browse()}>View Product Catalog</button></div></section>
   <section id="contact" className="support section-container section-space" aria-labelledby="support-heading"><h2 id="support-heading" className="centered-heading reveal">Flexible Support, <span>Based in Pakistan</span></h2><div className="support-grid"><button className="support-card reveal" onClick={() => contact("Call us")}><Icon name="phone" /><h3>Call us</h3><p>You can get in touch with our team via phone call.</p><span>Monday to Friday (9 AM to 10 PM)</span></button><button className="support-card reveal" onClick={() => contact("WhatsApp")}><Icon name="whatsapp" /><h3>WhatsApp</h3><p>You can get in touch with our team via WhatsApp.</p><span>Monday to Friday (9 AM to 10 PM)</span></button><a className="support-card reveal" href="mailto:hello@apkina.pk"><Icon name="email" /><h3>Email Support</h3><p>You can get in touch with our team via email support center.</p><span>hello@apkina.pk</span></a></div></section>
   <section id="newsletter" className="newsletter section-container section-space"><img className="newsletter-decoration left" src="/assets/newsletter-left.svg" width="224" height="533" alt="" /><img className="newsletter-decoration right" src="/assets/newsletter-right.svg" width="224" height="533" alt="" /><div className="newsletter-content reveal"><h2 className="silver-text">Your go-to Brand for<br /> Camera Accessories</h2><p>Subscribe to our newsletter to receive updates, and promotional offers.</p><form onSubmit={subscribe} className="newsletter-form"><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" name="email" type="email" autoComplete="email" required maxLength={254} value={email} placeholder="name@email.com" onChange={e => { setEmail(e.target.value); if (subscription !== "loading") setSubscription("idle"); }} disabled={subscription === "success"} /><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><button type="submit" disabled={subscription === "loading" || subscription === "success"}>{subscription === "loading" ? "Joining…" : subscription === "success" ? "Joined" : "Submit"}</button></form><p className={`form-message ${subscription}`} role="status" aria-live="polite">{formMessage}</p></div></section>
  </main>
  <footer className="footer section-space"><div className="section-container footer-content"><div className="footer-top"><div><a href="#home"><img className="footer-logo" src="/assets/logo.svg" alt="Apkina" width="242" height="60" /></a><p>For Pakistani Creators</p></div><div className="pakistan-badge"><Icon name="pakistan" />Proud Pakistani Brand</div></div><div className="footer-links"><div><h3>Products</h3>{categories.map(c => <button key={c.name} onClick={() => browse(c.name)}>{c.name}</button>)}</div><div><h3>Explore</h3><a href="#creators">For Creators</a><a href="#about">About Apkina</a><button onClick={blog}>Blog</button></div><div><h3>Support</h3><a href="/contact">Contact</a><button onClick={() => contact("Product Support")}>Product Support</button><button onClick={() => contact("Authorized Resellers")}>Authorized Resellers</button></div><div><h3>Legal</h3>{["Terms & Conditions", "Privacy Policy", "Cookie Usage"].map(name => <button key={name} onClick={() => legal(name)}>{name}</button>)}</div><div><h3>Social Media</h3>{["Instagram", "TikTok", "Facebook", "LinkedIn"].map(name => <button key={name} onClick={() => setInfo({ title: `Apkina on ${name}`, body: "Contact our team for Apkina’s current official social profiles and creator updates.", action: "Contact the team", subject: `Official ${name} profile` })}>{name}</button>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Apkina</span><a href="#home">Back to top ↑</a></div></div><span className="footer-watermark" aria-hidden="true">APKINA</span></footer>
  <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent className="mobile-sheet"><SheetTitle>Explore Apkina</SheetTitle><SheetDescription>Tools for your next creation.</SheetDescription><nav aria-label="Mobile navigation"><a href="#home" onClick={() => setMenuOpen(false)}>Home</a><button onClick={() => browse()}>Shop All Products</button>{categories.map(c => <button className="mobile-category" key={c.name} onClick={() => browse(c.name)}>{c.name}</button>)}<a href="#about" onClick={() => setMenuOpen(false)}>About</a><button onClick={() => { setMenuOpen(false); blog(); }}>Blog</button><a href="/contact" onClick={() => setMenuOpen(false)}>Contact</a></nav></SheetContent></Sheet>

  <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogTitle>Find your next creative tool</DialogTitle><DialogDescription>Search products and equipment categories.</DialogDescription><label className="search-field"><Icon name="search" /><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search lights, tripods, accessories…" aria-label="Search catalog" />{query && <button aria-label="Clear search" onClick={() => setQuery("")}>×</button>}</label><div className="search-results">{searchProducts.map(p=><button key={p.slug} className="search-product" onClick={()=>{setSearchOpen(false);router.push(`/products/${p.slug}`)}}><img src={assetImage(p.image)} alt="" width="70" height="70"/><span>{p.name}<small>Ask for current pricing</small></span><span>↗</span></button>)}{searchCategories.map(c => <button key={c.name} onClick={() => browse(c.name)}>{c.name}<span>Browse category →</span></button>)}{!searchProducts.length && searchCategories.length === 0 && <p className="no-results">No results for “{query}”. Try lights, tripods, or accessories.</p>}</div></DialogContent></Dialog>

  <Dialog open={!!info} onOpenChange={open => { if (!open) setInfo(null); }}><DialogContent className="info-dialog"><DialogTitle>{info?.title}</DialogTitle><DialogDescription>{info?.body}</DialogDescription>{info?.action ? <a className="pill dark" href={mail(info.subject || info.title)}>{info.action}</a> : <button className="pill dark" onClick={() => { setInfo(null); document.getElementById("newsletter")?.scrollIntoView({ behavior: "smooth" }); }}>Join the newsletter</button>}</DialogContent></Dialog>
 </>;
}
