"use client";
import {useState, type ReactNode} from "react";
import {usePathname} from "next/navigation";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {CartButton} from "./cart";
import {categories,whatsapp} from "@/lib/catalog";
export function StoreShell({children}:{children:ReactNode}) {
 const [open,setOpen]=useState(false);const path=usePathname();
 const links=[["/","Home"],["/shop","Shop"],["/#about","About"],["/blog","Blog"],["/contact","Contact"]];
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header scrolled inner-header"><a className="brand" href="/" aria-label="Apkina home"><img src="/assets/logo.svg" width="121" height="30" alt="Apkina"/></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([href,label])=><a key={href} href={href} aria-current={path===href?"page":undefined}>{label}</a>)}</nav><div className="header-actions"><CartButton/><a className="icon-button" href={whatsapp("Hello Apkina! I need some help choosing my gear.")} target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp"><img className="icon" src="/assets/whatsapp.svg" alt=""/></a><button className="icon-button menu-button" onClick={()=>setOpen(true)} aria-label="Open menu"><span/><span/></button></div></header><main id="main" className="store-main">{children}</main><footer className="store-footer"><div className="section-container"><div className="store-footer-top"><a href="/"><img src="/assets/logo.svg" alt="Apkina" width="182" height="45"/></a><p>For Pakistani Creators</p><a href={whatsapp("Hello Apkina! I have a question.")} target="_blank" rel="noopener noreferrer">Let’s talk about your next creation ↗</a></div><div className="store-footer-links"><div><p>Explore</p>{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}</div><div><p>Find your gear</p>{categories.map(c=><a key={c.slug} href={`/category/${c.slug}`}>{c.name}</a>)}</div><div><p>Get in touch</p><a href="tel:+923252849975">+92 325 2849975</a><a href="mailto:hello@apkina.pk">hello@apkina.pk</a><a href="/contact">Ask a product question</a></div></div><div className="store-footer-bottom"><span>© {new Date().getFullYear()} Apkina</span><span>Proud Pakistani Brand</span></div></div></footer><Sheet open={open} onOpenChange={setOpen}><SheetContent className="mobile-sheet"><SheetTitle>Explore Apkina</SheetTitle><SheetDescription>Tools for your next creation.</SheetDescription><nav aria-label="Mobile navigation">{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}{categories.map(c=><a className="mobile-category" key={c.slug} href={`/category/${c.slug}`}>{c.name}</a>)}</nav></SheetContent></Sheet></>;
}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.href?<a href={item.href}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}
