export const posts = [
 {slug:"one-light-better-stories",title:"One light. A whole new story.",category:"Lighting notes",read:"3 min read",image:"production",excerpt:"A simpler approach to a more considered frame. Start with one source, then build only what the shot needs.",sections:[
 {title:"Start with the frame you want",text:"Before adding equipment, choose the mood. Is the scene open and welcoming, or quiet and dramatic? Place your subject, compose the camera and look at the available light. Switch off any room lights that introduce an unwanted colour, then decide what your key light needs to do."},
 {title:"Move the light before you add another",text:"Begin with your light slightly above eye level and to one side of the subject. Make a short test recording. Move the light further to the side for more shape, or bring it closer to the camera axis for a more even look. Small changes in position can have a bigger effect than a more complicated setup."},
 {title:"Shape the shadows",text:"If the shadows feel too deep, try a white reflector or a plain white surface on the opposite side. If the scene feels too flat, remove that bounce. Keep the background a little further behind your subject so you have more control over where the light falls."},
 {title:"Make it repeatable",text:"Once the shot feels right, note the light position, camera settings and subject position. Take a quick behind-the-scenes photo. A repeatable setup makes your next tutorial, product video or interview easier to prepare and helps a series look consistent."}],link:"lighting"},
 {slug:"choose-your-first-tripod",title:"The quiet hero of your camera kit.",category:"Gear guide",read:"3 min read",image:"philosophy",excerpt:"What to consider before choosing a tripod for tutorials, interviews and the shots you make every day.",sections:[
 {title:"Choose for the camera you actually use",text:"Start with the total weight of your camera, lens and anything mounted on top. Compare that with the support’s rated payload, and ask about the head as well as the legs. A tripod should suit the complete setup, including accessories you regularly use."},
 {title:"Think about your most common shot",text:"A locked-off tutorial, an overhead demonstration and a moving interview shot place different demands on a support. Consider the working height, footprint and head movement you need. For regular video work, ask how smoothly the head pans and tilts with your camera attached."},
 {title:"Check the little things",text:"A quick-release plate, accessible controls and a comfortable carry size make a difference when you work alone. Check how the plate attaches to your camera and whether the tripod leaves room to reach the battery and cable connections."},
 {title:"Test before the real take",text:"Set up on a stable surface, check every lock and make sure the camera is balanced. Record a short pan, tilt or static take before you begin. If anything shifts or vibrates, adjust the support before trusting it with the full shoot."}],link:"tripods"},
 {slug:"cleaner-audio-small-setup",title:"Good sound starts before you press record.",category:"Creator essentials",read:"3 min read",image:"production",excerpt:"A few thoughtful changes to your room, microphone position and recording routine can make your next video easier to listen to.",sections:[
 {title:"Listen to the room first",text:"Pause and listen before setting the camera. Fans, road noise and empty-room echo can be easy to overlook. Choose the quietest available space and look for soft furnishings that help reduce reflections. Record a short test and listen with headphones."},
 {title:"Bring the microphone closer",text:"A microphone positioned near the speaker will usually give you a clearer starting point than one across the room. Keep it out of frame when needed, and test the distance with natural speech. Check that your microphone, cable and recording device are compatible before the session."},
 {title:"Protect the recording",text:"Listen for handling noise, cable movement and clothing brushing against the microphone. For outdoor recordings, choose suitable wind protection. Keep an eye on the input level so louder moments do not distort, and make another test if the speaker changes position."},
 {title:"Leave a little room for editing",text:"Record a few seconds of the room without speaking, and leave a short pause before and after each take. These small habits give you cleaner places to make edits. If a take has a distracting noise, recording it again is often simpler than trying to repair it later."}],link:"accessories"},
 {slug:"small-space-product-studio",title:"Small space. Thoughtful product photos.",category:"Behind the frame",read:"4 min read",image:"philosophy",excerpt:"Build a practical tabletop setup with a simple background, controlled light and space to experiment.",sections:[
 {title:"Keep your surface simple",text:"Choose a clean tabletop and an uncluttered background that suits the product. Leave enough room to move the light and camera independently. Prepare the object before the shoot: dust, fingerprints and creases are easier to remove now than in editing."},
 {title:"Watch the reflections",text:"Glossy products show the light source and parts of the room. Move the light slowly while watching the camera view, and notice how highlights travel across the surface. A larger, diffused source can create a gentler reflection. Dark or white cards can help define an edge without adding another lamp."},
 {title:"Build a short shot list",text:"Capture a clear overall image, a useful detail and a view that explains how the product is used. Keep the camera position and background consistent across a collection. Leave some breathing room around the object so the images can work in different page layouts."},
 {title:"Check the result at the size people will see",text:"Review your images on a phone as well as your editing screen. Can you recognise the product, understand its shape and see the important detail? Select the clearest frames, keep your edit consistent and avoid changes that misrepresent the product’s colour or finish."}],link:"modifiers"},
];
